#!/usr/bin/perl
# textmoji v1.0
# buraksimsek32@gmail.com
# alec.muffett@gmail.com
use strict;
use warnings;
use Getopt::Long qw(GetOptions);

my %dict;
my $sep = " ";
my $h = 0;
my $l = 0;
my $n = 0;
my $p = 0;

GetOptions(
  "h|help" => \$h,
  "l" => \$l,
  "n" => \$n,
  "p" => \$p
) or die("Error in command line arguments\n");

while (<DATA>) {
  s/\s+/ /go;
  s/\s$//go;
  next if /^\s*(#.*)?$/;
  (my $keys, my $value) = split(" ", $_, 2);
  foreach my $key (split(/,/o, $keys)) {
    $dict{$key} = $value;
  }
}

if ($l) {
  foreach my $key (sort keys %dict) {
    printf("%-20s %s\n", $key, $dict{$key});
  }
  exit(0);
}

if ($h || !@ARGV) {
  print <<"EOT";
Hello, some manpage stuff goes here!
EOT
  exit(0);
}

if ($p) { # -p argument, separate (not -np)
  close(STDOUT);
  open(STDOUT, "|pbcopy") || die "$0: open: $!\n";
}

if ($n) { # -n argument, see -s switch
  $sep = "\n";
}

my @arguments = @ARGV;
my $name;
while (@arguments) {
  $name = shift(@arguments);
  print ( $dict{$name} || "#NOTFOUND=$name" );
  print $sep if (@arguments);
}
print "\n";
__END__;
# basic ones
test1 :-)
test2,nickname :-(

# extra whitespace will get purged
test3    %-|   :-P

# real data
shrug ¯\_(ツ)_/¯
tf,tableflip (╯°□°）╯︵ ┻━┻
fixtable ┬─┬﻿ ノ( ゜-゜ノ)
meh ¯\(°_o)/¯
cheers （ ^_^）o自自o（^_^ ）
